# github: [your-github-username]
# patreon: [your-patreon-username]
# open_collective: [your-open-collective]
# ko_fi: [your-ko-fi]
# tidelift: [package-tidelift]
# community_bridge: [community-bridge]
# liberapay: [liberapay-username]
# issuehunt: [issuehunt]
# otechie: [your-otechie-username]
custom: ['https://yourcustomfunding.com']
